const numbers = document.querySelectorAll('.number')
const operators = document.querySelectorAll('.operator')
const deleter = document.getElementById('delete')
const clearer = document.getElementById('clear')
const equals = document.getElementsByClassName('equals')
const pastInput = document.getElementById('past-input')
const currentInput = document.getElementById('current-input')